name: Dejavu - Node.js Build and Release Workflow

on:
  release:
    types: [published]
  repository_dispatch:
    types: [publish_binary]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Node.js 24 LTS
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn

    - name: Extract version from payload
      id: get_version
      if: ${{ github.event_name == 'repository_dispatch' }}
      run: echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT

    - name: Get Version For Release
      id: get_version_release
      if: ${{ github.event_name != 'repository_dispatch' }}
      uses: battila7/get-version-action@v2.2.1

    - name: Determine Version
      id: set_version
      run: |
        if [ -n "${{ steps.get_version.outputs.version }}" ]; then
          echo "version=${{ steps.get_version.outputs.version }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ steps.get_version_release.outputs.version }}" ]; then
          echo "version=${{ steps.get_version_release.outputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "Error: Version is not set."
          exit 1
        fi

    - name: Build Dejavu App
      run: DISABLE_FAVICONS=1 yarn build:dejavu:app

    - name: Zip the dist folder
      run: |
        zip -r dist-${{ steps.set_version.outputs.version }}.zip ./packages/dejavu-main/dist

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      with:
        name: dejavu-dist-${{ steps.set_version.outputs.version }}
        path: dist-${{ steps.set_version.outputs.version }}.zip
        retention-days: 7 # 可选：设置保留天数，默认通常是 90 天
        if-no-files-found: error # 可选：如果找不到文件则让流水线报错
